apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}